USE CovidHistorico2;
GO

ALTER DATABASE CovidHistorico2 ADD FILEGROUP FG_ANTES_2020;
ALTER DATABASE CovidHistorico2 ADD FILEGROUP FG_2020;
ALTER DATABASE CovidHistorico2 ADD FILEGROUP FG_2021;
ALTER DATABASE CovidHistorico2 ADD FILEGROUP FG_2022_MAS;


ALTER DATABASE CovidHistorico2
ADD FILE (
    NAME = FG_ANTES_2020_dat,
    FILENAME = 'D:\Escuela\Superior\S_SEMESTRE 6\bdd\baseCovid\PRACTICA3\FG_ANTES_2020.ndf',
    SIZE = 10MB
)
TO FILEGROUP FG_ANTES_2020;

ALTER DATABASE CovidHistorico2
ADD FILE (
    NAME = FG_2020_dat,
    FILENAME = 'D:\Escuela\Superior\S_SEMESTRE 6\bdd\baseCovid\PRACTICA3\FG_2020.ndf',
    SIZE = 10MB
)
TO FILEGROUP FG_2020;

ALTER DATABASE CovidHistorico2
ADD FILE (
    NAME = FG_2021_dat,
    FILENAME = 'D:\Escuela\Superior\S_SEMESTRE 6\bdd\baseCovid\PRACTICA3\FG_2021.ndf',
    SIZE = 10MB
)
TO FILEGROUP FG_2021;

ALTER DATABASE CovidHistorico2
ADD FILE (
    NAME = FG_2022_MAS_dat,
    FILENAME = 'D:\Escuela\Superior\S_SEMESTRE 6\bdd\baseCovid\PRACTICA3\FG_2022_MAS.ndf',
    SIZE = 10MB
)
TO FILEGROUP FG_2022_MAS;

CREATE PARTITION FUNCTION pf_anio (DATE)
AS RANGE RIGHT FOR VALUES
(
    '2020-01-01',
    '2021-01-01',
    '2022-01-01'
);


CREATE PARTITION SCHEME ps_anio
AS PARTITION pf_anio
TO
(
    FG_ANTES_2020,
    FG_2020,
    FG_2021,
    FG_2022_MAS
);


CREATE TABLE covid_staging (
    FECHA_ACTUALIZACION VARCHAR(50),
    ID_REGISTRO VARCHAR(50),
    ORIGEN VARCHAR(10),
    SECTOR VARCHAR(10),
    ENTIDAD_UM VARCHAR(10),
    SEXO VARCHAR(10),
    ENTIDAD_NAC VARCHAR(10),
    ENTIDAD_RES VARCHAR(100),
    MUNICIPIO_RES VARCHAR(10),
    TIPO_PACIENTE VARCHAR(10),
    FECHA_INGRESO VARCHAR(50),
    FECHA_SINTOMAS VARCHAR(50),
    FECHA_DEF VARCHAR(50),
    INTUBADO VARCHAR(10),
    NEUMONIA VARCHAR(10),
    EDAD VARCHAR(10),
    NACIONALIDAD VARCHAR(10),
    EMBARAZO VARCHAR(10),
    HABLA_LENGUA_INDIG VARCHAR(10),
    INDIGENA VARCHAR(10),
    DIABETES VARCHAR(10),
    EPOC VARCHAR(10),
    ASMA VARCHAR(10),
    INMUSUPR VARCHAR(10),
    HIPERTENSION VARCHAR(10),
    OTRA_COM VARCHAR(10),
    CARDIOVASCULAR VARCHAR(10),
    OBESIDAD VARCHAR(10),
    RENAL_CRONICA VARCHAR(10),
    TABAQUISMO VARCHAR(10),
    OTRO_CASO VARCHAR(10),
    TOMA_MUESTRA_LAB VARCHAR(10),
    RESULTADO_PCR VARCHAR(10),
    RESULTADO_PCR_COINFECCION VARCHAR(10),
    TOMA_MUESTRA_ANTIGENO VARCHAR(10),
    RESULTADO_ANTIGENO VARCHAR(10),
    CLASIFICACION_FINAL_COVID VARCHAR(10),
    CLASIFICACION_FINAL_FLU VARCHAR(10),
    MIGRANTE VARCHAR(10),
    PAIS_NACIONALIDAD VARCHAR(100),
    PAIS_ORIGEN VARCHAR(100),
    UCI VARCHAR(10)
);

BULK INSERT covid_staging
FROM 'D:\Escuela\Superior\S_SEMESTRE 6\bdd\baseCovid\COVID19MEXICO2024.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    CODEPAGE = 'ACP',
    TABLOCK
);

SELECT TOP 5 *
FROM covid_staging;


CREATE TABLE covid_particionado (
    FECHA_INGRESO DATE NOT NULL,
    ENTIDAD_RES VARCHAR(50),
    EDAD INT
)
ON ps_anio(FECHA_INGRESO);


INSERT INTO covid_particionado
(
    FECHA_INGRESO,
    ENTIDAD_RES,
    EDAD
)
SELECT
    TRY_CONVERT(DATE, REPLACE(FECHA_INGRESO,'"','')),
    REPLACE(ENTIDAD_RES,'"',''),
    TRY_CONVERT(INT, REPLACE(EDAD,'"',''))
FROM covid_staging
WHERE TRY_CONVERT(DATE, REPLACE(FECHA_INGRESO,'"',''))
IS NOT NULL;

CREATE CLUSTERED INDEX idx_fecha
ON covid_particionado(FECHA_INGRESO)
ON ps_anio(FECHA_INGRESO);


/*Ver rangos*/
SELECT pf.name, prv.value
FROM sys.partition_functions pf
JOIN sys.partition_range_values prv
ON pf.function_id = prv.function_id
WHERE pf.name = 'pf_anio';

/*ver filas por particion*/
SELECT
    p.partition_number,
    p.rows
FROM sys.partitions p
WHERE p.object_id = OBJECT_ID('covid_particionado')
AND p.index_id IN (0,1);
